### PR TITLE
Update README.txt

### PR DESCRIPTION
**Pull request by bradleeedmondson**
remove readme and replace with pointers to authoritative/maintained repositories

### CODE REVIEW

**Review by wking — APPROVED** [review]
This looks fine to me, although we could get clickable links by changing `.txt` to `.md`.

**Comment by bradleeedmondson** [comment]
assuming no reason not to change from readme.txt to readme.md, that sound good to me. @goneall please object if necessary, otherwise I will include this in the PR.

**Review by wking — APPROVED** [review]

**Review by jlovejoy — APPROVED** [review]
this looks good. we may update the date (hopefully will be ~Dec 28th!) and I think we decided to at that point, change the repo name to "license-list-archived" or something like that, at which point we can simply remove the last sentence

**Comment by goneall** [comment]
> assuming no reason not to change from readme.txt to readme.md

No objections here

**Pull request merged**
